BookManagement/Controllers/AdminstrationController.cs
using BookManagement.Models;
using BookManagement.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookManagement.Controllers
{
    public class AdminstrationController : Controller
    {
        private readonly RoleManager<ApplicationRole> roleManager;

        public AdminstrationController(RoleManager<ApplicationRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Check if the role already exists
                bool roleExist = await roleManager.RoleExistsAsync(model.RoleName);
                if (roleExist)
                {
                    // MARK: Added an error message to the ModelState instead of returning JSON
                    ModelState.AddModelError(string.Empty, "Role already exists!");
                }
                else
                {
                    ApplicationRole role = new ApplicationRole
                    {
                        Name = model.RoleName,
                        Description = model.Description,
                        
                    };
                    var result = await roleManager.CreateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    // MARK: Added logic to include any identity errors into ModelState
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            // MARK: If validation fails or role exists, return the view with validation messages
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllRoles()
        {
            List<ApplicationRole> roles = await roleManager.Roles.ToListAsync();
            
            return View(roles);
        }
        [HttpGet]
        
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
           
                return View("NotFound");
            }

            var result = await roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                // Role deletion successful
                return RedirectToAction("AllRoles"); // Redirect to the roles list page
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            // If we reach here, something went wrong, return to the view
            return View("AllRoles", await roleManager.Roles.ToListAsync());
        }
    }
}

BookManagement/Controllers/BookController.cs
using BookManagement.Models;
using BookManagement.Repositery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookManagement.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepositery bookRepositery;
        private readonly IBorrowRecordRepositery borrowingRecord;

        public BookController(IBookRepositery bookRepositery, IBorrowRecordRepositery borrowingRecord) {
            this.bookRepositery = bookRepositery;
            this.borrowingRecord = borrowingRecord;
        }
        // GET: BookController
       // [Authorize]
        public ActionResult Index()
        {
            return View("Index",bookRepositery.GetAll());
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View("Details", bookRepositery.GetById(id));
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book book)
        {
           
            try
            {
                if (ModelState.IsValid)
                {
                    bookRepositery.Add(book);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                // Handel Some Error
            }
                return View("Create",book);
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View("Edit",bookRepositery.GetById(id));
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bookRepositery.Update(book);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {

            }
                return View("Edit",book);
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View("Delete",bookRepositery.GetById(id));
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id,Book book)
        {
                Book book1 = bookRepositery.GetById(id);
            try
            {

                if (borrowingRecord.HasBorrowRecordsBook(id))
                {
                    ModelState.Clear();
                    ModelState.AddModelError("", "Cant Remove this book it's borrowed.  ");
                    
                    return View(book1);
                }

                if (book1 == null)
                    return NotFound();
                
                
                bookRepositery.Remove(book1);
                return RedirectToAction(nameof(Index));
                
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Cant Remove this book some error events  ");
            }
            
                return View(book1);
        }
    }
}

BookManagement/Controllers/MemberController.cs
using BookManagement.Models;
using BookManagement.Repositery;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookManagement.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberRepositery member;
        private readonly IBorrowRecordRepositery borrowRecord;
        public MemberController(IMemberRepositery member, IBorrowRecordRepositery borrowRecord) { 
        
            this.member = member;
            this.borrowRecord = borrowRecord;
        }
        // GET: MemberController
        public ActionResult Index()
        {
            return View(member.GetAll());
        }

        // GET: MemberController/Details/5
        public ActionResult Details(int id)
        {
            return View(member.GetById(id));
        }

        // GET: MemberController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MemberController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member m)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    member.Add(m);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
            }
                return View();
        }

        // GET: MemberController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(member.GetById(id));
        }

        // POST: MemberController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Member collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    member.Update(collection);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
            }
                return View();
        }

        // GET: MemberController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(member.GetById(id));
        }

        // POST: MemberController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            var m = member.GetById(id);
            try
            {
                if (borrowRecord.HasBorrowRecordsMember(id))
                {
                    ModelState.Clear();
                    ModelState.AddModelError("", "Can't Remove this member Until Retirve Book");
                    return View(m);
                }
                if (member == null)
                    return NotFound();

                member.Remove(m);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookManagement/Controllers/RecordBookMemberController.cs
using BookManagement.Models;
using BookManagement.Repositery;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookManagement.Controllers
{
    public class RecordBookMemberController : Controller
    {
        private readonly IBorrowRecordRepositery borrowRecordRepositery;
        private readonly IMemberRepositery memberrepositery;
        private readonly IBookRepositery bookRepositery;

        public RecordBookMemberController(IBorrowRecordRepositery borrowRecordRepositery,IMemberRepositery memberrepositery, IBookRepositery bookRepositery)
        {
            this.borrowRecordRepositery = borrowRecordRepositery;
            this.memberrepositery = memberrepositery;
            this.bookRepositery = bookRepositery;
        }
        // GET: RecordBookMemberController
        public ActionResult Index()
        {
            return View(borrowRecordRepositery.GetAll());
        }



        // GET: RecordBookMemberController/Create
        public ActionResult Create()
        {
            ViewBag.BookId = new SelectList(bookRepositery.GetAll(), "Id", "Title");
            ViewBag.MemberId = new SelectList(memberrepositery.GetAll(), "Id", "Name");
            return View();
        }

        // POST: RecordBookMemberController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BorrowingRecord collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    borrowRecordRepositery.Add(collection);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {

            }
                return View(collection);
        }

       

       

        // GET: RecordBookMemberController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(borrowRecordRepositery.GetBorrowingRecordWithInclude(id));
        }

        // POST: RecordBookMemberController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
             BorrowingRecord borrowingRecord = borrowRecordRepositery.GetById(id);
            try
            {
                if(borrowingRecord == null)
                    return NotFound();
                borrowRecordRepositery.Remove(borrowingRecord);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(borrowingRecord);
            }
        }
    }
}

BookManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <partial name="_Partial"></partial>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookManagement/Views/Shared/_Partial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookManagement</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Adminstration" asp-action="AllRoles">AllRoles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Member</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RecordBookMember" asp-action="Index">RecordBookMember</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Welcome @User.Identity.Name</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                }


            </ul>
        </div>
    </div>
</nav>